from django.urls import path

from .views import (
    index,
    UserListView,
    UserDetailView,
    PetListView,
    ActivityListView,
    HealthEventListView,
    UserCreateView,
    PetCreateView,
    ActivityCreateView,
    HealthEventCreateView,
    UserUpdateView,
    UserDeleteView,
    PetDetailView,
    PetUpdateView,
    PetDeleteView,
    toggle_assign_to_pet, ActivityDetailView, ActivityUpdateView, ActivityDeleteView, HealthEventDetailView,
    HealthEventUpdateView, HealthEventDeleteView, StatusListView, StatusCreateView, StatusUpdateView, StatusDeleteView,
    PriorityListView, PriorityCreateView, PriorityUpdateView, PriorityDeleteView, SpeciesListView, SpeciesCreateView,
    SpeciesUpdateView, SpeciesDeleteView, SignUpView
)

urlpatterns = [
    path("", index, name="index"),
    path("users/", UserListView.as_view(), name="user-list"),
    path("users/<int:pk>/", UserDetailView.as_view(), name="user-detail"),
    path("users/<int:pk>/update/", UserUpdateView.as_view(), name="user-update"),
    path("users/<int:pk>/delete/", UserDeleteView.as_view(), name="user-delete"),
    path("users/create/", UserCreateView.as_view(), name="user-create"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("pets/", PetListView.as_view(), name="pet-list"),
    path("pets/create/", PetCreateView.as_view(), name="pet-create"),
    path("pets/<int:pk>/", PetDetailView.as_view(), name="pet-detail"),
    path("pets/<int:pk>/update/", PetUpdateView.as_view(), name="pet-update"),
    path("pets/<int:pk>/delete/", PetDeleteView.as_view(), name="pet-delete"),
    path(
        "pets/<int:pk>/toggle-assign/",
        toggle_assign_to_pet,
        name="toggle-pet-assign",
    ),
    path("activities/", ActivityListView.as_view(), name="activity-list"),
    path("activities/create/", ActivityCreateView.as_view(), name="activity-create"),
    path("activities/<int:pk>/", ActivityDetailView.as_view(), name="activity-detail"),
    path("activities/<int:pk>/update", ActivityUpdateView.as_view(), name="activity-update"),
    path("activities/<int:pk>/delete", ActivityDeleteView.as_view(), name="activity-delete"),
    path("healthevents/", HealthEventListView.as_view(), name="healthevent-list"),
    path("healthevents/create/", HealthEventCreateView.as_view(), name="healthevent-create"),
    path("healthevents/<int:pk>/", HealthEventDetailView.as_view(), name="healthevent-detail"),
    path("healthevents/<int:pk>/update", HealthEventUpdateView.as_view(), name="healthevent-update"),
    path("healthevents/<int:pk>/delete", HealthEventDeleteView.as_view(), name="healthevent-delete"),
    path("statuses/", StatusListView.as_view(), name="status-list"),
    path("statuses/create/", StatusCreateView.as_view(), name="status-create"),
    path("statuses/<int:pk>/update", StatusUpdateView.as_view(), name="status-update"),
    path("statuses/<int:pk>/delete", StatusDeleteView.as_view(), name="status-delete"),
    path("priorities/", PriorityListView.as_view(), name="priority-list"),
    path("priorities/create/", PriorityCreateView.as_view(), name="priority-create"),
    path("priorities/<int:pk>/update", PriorityUpdateView.as_view(), name="priority-update"),
    path("priorities/<int:pk>/delete", PriorityDeleteView.as_view(), name="priority-delete"),
    path("species/", SpeciesListView.as_view(), name="species-list"),
    path("species/create/", SpeciesCreateView.as_view(), name="species-create"),
    path("species/<int:pk>/update", SpeciesUpdateView.as_view(), name="species-update"),
    path("species/<int:pk>/delete", SpeciesDeleteView.as_view(), name="species-delete"),
]

app_name = "core"
